version: '3'
services:
    app:
        container_name: docker-test
        restart: always
        build: ./node
        ports:  
            - '80:3000'
            - '8088:8088'
        links: 
            - 'mysql'
    mysql:
        container_name: mysql_debug
        restart: always
        build: ./mysql
        ports:
          - "3306:3306"
    phpmyadmin:
        container_name: phpmyadmin_debug
        restart: always
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_PORT: 3306
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: password
        ports: 
            - "5000:80"

    